name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or the version of Node.js your project requires

      - name: Install dependencies
        run: npm ci  # or 'npm install' if you are not using lock files

      - name: Start the application (Optional if your app needs to be served)
        run: npm start &
        env:
          CI: true

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5  # Use the latest version of the Cypress GitHub Action
        with:
          record: false  # Set this to 'true' if you are recording on the Cypress Dashboard
        env:
          CI: true
